Repository jupyterlab-contrib/rise, pull requests merged in 2023-02, with the labels that each got.

#9 Fix for #8
  app/webpack.config.js
  app/webpack.config.watch.js
  packages/application/src/plugins/rise.ts
  packages/application/tsconfig.json
  packages/lab/package.json
  packages/lab/tsconfig.json
  tsconfigbase.json
Labels: bug

#16 Add numpy and ipywidgets to the binder environment
  .github/workflows/binder-on-pr.yml
  binder/environment.yml
Labels: documentation

#19 Fixes Syntax Highlighting
  app/package.json
  package.json
  packages/application/package.json
  packages/application/src/plugins/rise.ts
  tsconfigbase.json
  yarn.lock
Labels: bug

#20 Fix bumping version
  .eslintignore
  .github/workflows/check-release.yml
  .prettierignore
  examples/jupytext-python.py
  jupyterlab_rise/__init__.py
  jupyterlab_rise/app.py
  pyproject.toml
  scripts/bump_version.py
  setup.py
  ui-tests/jupyter_server_test_config.py
Labels: bug, maintenance

#21 Fix shell pollution by third party extension
  packages/application/src/app/index.ts
  packages/application/src/plugins/rise.ts
Labels: bug

#22 Fix bump version script
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  README.md
  RELEASE.md
  pyproject.toml
  scripts/bump_version.py
Labels: bug, maintenance
