Repository jupyterlab-contrib/rise, pull requests merged in 2024-12, with the labels that each got.

#106 Fix CI
  README.md
  yarn.lock
Labels: maintenance

#107 Update extension template
  .copier-answers.yml
  .github/workflows/binder-on-pr.yml
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  RELEASE.md
  package.json
  pyproject.toml
  ui-tests/README.md
  ui-tests/package.json
  yarn.lock
Labels: maintenance

#80 Add Mermaid dependecies to application/package.json
  app/index.js
  app/package.json
  examples/mermaid.ipynb
  packages/application/package.json
  packages/lab/package.json
  pyproject.toml
  yarn.lock
Labels: bug

#108 Fix dev install
  README.md
Labels: documentation

#91 Fix dataframes and text size in slides
  packages/application/style/base.css
Labels: bug
